//! `cargo hwhkit dev` — generate + run a local docker-compose stack
//! covering the integrations enabled in the project's `hwhkit.toml`
//! (or, when absent, sensible defaults).
//!
//! The compose file is written to `target/.hwhkit-dev/docker-compose.yml`
//! before invoking `docker compose -f ...`, so the project tree stays
//! tidy. Users who want to keep the file in source control can run
//! `cargo hwhkit dev generate --out docker-compose.dev.yml`.

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Default, Deserialize, Serialize)]
pub struct DevStack {
    #[serde(default)]
    pub project: Project,
    #[serde(default)]
    pub services: Services,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct Project {
    #[serde(default = "default_project_name")]
    pub name: String,
}

fn default_project_name() -> String {
    "hwhkit-dev".to_string()
}

impl Default for Project {
    fn default() -> Self {
        Self {
            name: default_project_name(),
        }
    }
}

#[derive(Debug, Clone, Default, Deserialize, Serialize)]
pub struct Services {
    #[serde(default)]
    pub postgres: ServiceToggle,
    #[serde(default)]
    pub redis: ServiceToggle,
    #[serde(default)]
    pub nats: ServiceToggle,
    #[serde(default)]
    pub minio: ServiceToggle,
    #[serde(default)]
    pub qdrant: ServiceToggle,
    #[serde(default)]
    pub mongodb: ServiceToggle,
}

#[derive(Debug, Clone, Default, Deserialize, Serialize)]
pub struct ServiceToggle {
    #[serde(default)]
    pub enabled: bool,
    #[serde(default)]
    pub image: Option<String>,
    #[serde(default)]
    pub port: Option<u16>,
}

impl DevStack {
    /// Load `hwhkit.toml` if present, otherwise return a default that
    /// enables Postgres + Redis (the most common local-dev pairing).
    pub fn load(path: &Path) -> Result<Self> {
        if !path.exists() {
            let mut s = Self::default();
            s.services.postgres.enabled = true;
            s.services.redis.enabled = true;
            return Ok(s);
        }
        let raw = fs::read_to_string(path)
            .with_context(|| format!("failed to read {}", path.display()))?;
        let parsed: DevStack =
            toml::from_str(&raw).with_context(|| format!("failed to parse {}", path.display()))?;
        Ok(parsed)
    }
}

/// Render `docker-compose.yml` body without writing it.
pub fn render_compose(stack: &DevStack) -> String {
    let mut out = String::new();
    out.push_str("# generated by `cargo hwhkit dev` — edit hwhkit.toml, not this file\n");
    out.push_str(&format!("name: {}\n", stack.project.name));
    out.push_str("services:\n");

    if stack.services.postgres.enabled {
        let img = stack
            .services
            .postgres
            .image
            .as_deref()
            .unwrap_or("postgres:16-alpine");
        let port = stack.services.postgres.port.unwrap_or(5432);
        out.push_str(&format!(
            "  postgres:\n    image: {img}\n    environment:\n      POSTGRES_USER: hwhkit\n      POSTGRES_PASSWORD: hwhkit\n      POSTGRES_DB: hwhkit\n    ports:\n      - \"{port}:5432\"\n    healthcheck:\n      test: [\"CMD-SHELL\", \"pg_isready -U hwhkit\"]\n      interval: 5s\n      retries: 12\n    volumes:\n      - hwhkit_pg_data:/var/lib/postgresql/data\n"
        ));
    }

    if stack.services.redis.enabled {
        let img = stack
            .services
            .redis
            .image
            .as_deref()
            .unwrap_or("redis:7-alpine");
        let port = stack.services.redis.port.unwrap_or(6379);
        out.push_str(&format!(
            "  redis:\n    image: {img}\n    ports:\n      - \"{port}:6379\"\n    healthcheck:\n      test: [\"CMD\", \"redis-cli\", \"ping\"]\n      interval: 5s\n      retries: 12\n"
        ));
    }

    if stack.services.nats.enabled {
        let img = stack
            .services
            .nats
            .image
            .as_deref()
            .unwrap_or("nats:2.10-alpine");
        let port = stack.services.nats.port.unwrap_or(4222);
        out.push_str(&format!(
            "  nats:\n    image: {img}\n    command: [\"-js\"]\n    ports:\n      - \"{port}:4222\"\n      - \"8222:8222\"\n"
        ));
    }

    if stack.services.minio.enabled {
        let img = stack
            .services
            .minio
            .image
            .as_deref()
            .unwrap_or("minio/minio:latest");
        let port = stack.services.minio.port.unwrap_or(9000);
        out.push_str(&format!(
            "  minio:\n    image: {img}\n    command: server /data --console-address \":9001\"\n    environment:\n      MINIO_ROOT_USER: hwhkit\n      MINIO_ROOT_PASSWORD: hwhkit-secret\n    ports:\n      - \"{port}:9000\"\n      - \"9001:9001\"\n    volumes:\n      - hwhkit_minio_data:/data\n"
        ));
    }

    if stack.services.qdrant.enabled {
        let img = stack
            .services
            .qdrant
            .image
            .as_deref()
            .unwrap_or("qdrant/qdrant:latest");
        let port = stack.services.qdrant.port.unwrap_or(6333);
        out.push_str(&format!(
            "  qdrant:\n    image: {img}\n    ports:\n      - \"{port}:6333\"\n      - \"6334:6334\"\n    volumes:\n      - hwhkit_qdrant_data:/qdrant/storage\n"
        ));
    }

    if stack.services.mongodb.enabled {
        let img = stack.services.mongodb.image.as_deref().unwrap_or("mongo:7");
        let port = stack.services.mongodb.port.unwrap_or(27017);
        out.push_str(&format!(
            "  mongodb:\n    image: {img}\n    environment:\n      MONGO_INITDB_ROOT_USERNAME: hwhkit\n      MONGO_INITDB_ROOT_PASSWORD: hwhkit\n    ports:\n      - \"{port}:27017\"\n    volumes:\n      - hwhkit_mongo_data:/data/db\n"
        ));
    }

    out.push_str("\nvolumes:\n");
    out.push_str("  hwhkit_pg_data:\n");
    out.push_str("  hwhkit_minio_data:\n");
    out.push_str("  hwhkit_mongo_data:\n");
    out.push_str("  hwhkit_qdrant_data:\n");

    out
}

/// Render `docker-compose.yml` and write it to a stable path under
/// `target/.hwhkit-dev/`. Returns the absolute path to the file.
pub fn write_compose(stack: &DevStack) -> Result<PathBuf> {
    let dir = std::env::current_dir()
        .map(|d| d.join("target").join(".hwhkit-dev"))
        .context("cannot resolve current dir")?;
    fs::create_dir_all(&dir).with_context(|| format!("failed to create {}", dir.display()))?;
    let path = dir.join("docker-compose.yml");
    fs::write(&path, render_compose(stack))
        .with_context(|| format!("failed to write {}", path.display()))?;
    Ok(path)
}
