use anyhow::{Context, Result};
use clap::{Parser, Subcommand, ValueEnum};
use std::{
    fs,
    path::{Path, PathBuf},
};

#[derive(Parser, Debug)]
#[command(author, version, about = "HwhKit project scaffolding")]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand, Debug)]
enum Commands {
    Init {
        name: String,
        #[arg(long, default_value = "minimal-api")]
        template: TemplateKind,
    },
}

#[derive(Copy, Clone, Debug, ValueEnum)]
enum TemplateKind {
    MinimalApi,
    ApiGrpc,
    RealtimeEvent,
}

fn main() -> Result<()> {
    let cli = Cli::parse();

    match cli.command {
        Commands::Init { name, template } => init_project(&name, template),
    }
}

fn init_project(name: &str, template: TemplateKind) -> Result<()> {
    let root = PathBuf::from(name);
    let package_name = package_name_from_root(&root)?;
    create_common_layout(&root)?;

    match template {
        TemplateKind::MinimalApi => render_minimal_api(&root, &package_name)?,
        TemplateKind::ApiGrpc => render_api_grpc(&root, &package_name)?,
        TemplateKind::RealtimeEvent => render_realtime_event(&root, &package_name)?,
    }

    write_file(
        &root.join("README.md"),
        &format!(
            "# {package_name}\n\nGenerated by `cargo hwhkit init --template {}`.\n",
            template_name(template)
        ),
    )?;

    println!("initialized project: {}", root.display());
    println!("template: {}", template_name(template));
    Ok(())
}

fn create_common_layout(root: &Path) -> Result<()> {
    fs::create_dir_all(root.join("src/routes"))?;
    fs::create_dir_all(root.join("src/domain"))?;
    fs::create_dir_all(root.join("config"))?;
    fs::create_dir_all(root.join("tests"))?;
    fs::create_dir_all(root.join(".github/workflows"))?;

    write_file(
        &root.join(".env.example"),
        "HWHKIT__SERVER__PORT=3000\nHWHKIT__OBSERVABILITY__LOGGING__LEVEL=info\n",
    )?;
    write_file(
        &root.join("Dockerfile"),
        "FROM rust:1.84 as builder\nWORKDIR /app\nCOPY . .\nRUN cargo build --release\n\nFROM debian:bookworm-slim\nCOPY --from=builder /app/target/release/APP_NAME /usr/local/bin/app\nCMD [\"/usr/local/bin/app\"]\n",
    )?;
    write_file(
        &root.join("justfile"),
        "run:\n    cargo run\n\ntest:\n    cargo test\n\nfmt:\n    cargo fmt --all\n",
    )?;
    write_file(
        &root.join(".github/workflows/ci.yml"),
        "name: ci\non: [push, pull_request]\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: dtolnay/rust-toolchain@stable\n      - run: cargo test --all\n",
    )?;
    write_file(
        &root.join("tests/smoke.rs"),
        "#[test]\nfn smoke() {\n    assert!(true);\n}\n",
    )?;

    Ok(())
}

fn render_minimal_api(root: &Path, name: &str) -> Result<()> {
    write_file(
        &root.join("Cargo.toml"),
        &cargo_toml(
            name,
            &[
                "config-v2",
                "postgres",
                "redis",
                "mongodb",
                "nats",
                "qdrant",
                "neo4j",
            ],
        ),
    )?;
    write_main(root)?;
    write_standard_app(root)?;
    write_file(&root.join("src/routes/mod.rs"), "pub mod health;\n")?;
    write_file(
        &root.join("src/routes/health.rs"),
        "pub async fn health() -> &'static str {\n    \"ok\"\n}\n",
    )?;
    write_file(&root.join("src/domain/mod.rs"), "")?;
    write_config_files(root, "dev")?;
    patch_docker_app_name(root, name)?;
    Ok(())
}

fn render_api_grpc(root: &Path, name: &str) -> Result<()> {
    fs::create_dir_all(root.join("proto/app/v1"))?;
    fs::create_dir_all(root.join("scripts"))?;

    write_file(
        &root.join("Cargo.toml"),
        &cargo_toml(
            name,
            &[
                "config-v2",
                "transport-grpc",
                "postgres",
                "redis",
                "mongodb",
                "nats",
            ],
        ),
    )?;
    write_main(root)?;
    write_standard_app(root)?;
    write_file(
        &root.join("src/routes/mod.rs"),
        "pub mod health;\npub mod rest;\n",
    )?;
    write_file(
        &root.join("src/routes/health.rs"),
        "pub async fn health() -> &'static str {\n    \"ok\"\n}\n",
    )?;
    write_file(
        &root.join("src/routes/rest.rs"),
        "pub async fn hello() -> &'static str {\n    \"hello from rest\"\n}\n",
    )?;
    write_file(
        &root.join("proto/app/v1/service.proto"),
        "syntax = \"proto3\";\npackage app.v1;\n\nservice AppService {\n  rpc Ping (PingRequest) returns (PingReply);\n}\n\nmessage PingRequest {\n  string name = 1;\n}\n\nmessage PingReply {\n  string message = 1;\n}\n",
    )?;
    write_file(
        &root.join("scripts/gen-proto.sh"),
        "#!/usr/bin/env bash\nset -euo pipefail\n\necho \"Integrate tonic-build here for proto generation\"\n",
    )?;
    write_config_files(root, "dev")?;
    patch_docker_app_name(root, name)?;
    Ok(())
}

fn render_realtime_event(root: &Path, name: &str) -> Result<()> {
    fs::create_dir_all(root.join("src/realtime"))?;

    write_file(
        &root.join("Cargo.toml"),
        &cargo_toml(
            name,
            &[
                "config-v2",
                "transport-ws",
                "nats",
                "redis",
                "mongodb",
                "qdrant",
            ],
        ),
    )?;
    write_main(root)?;
    write_standard_app(root)?;
    write_file(
        &root.join("src/routes/mod.rs"),
        "pub mod health;\npub mod ws;\n",
    )?;
    write_file(
        &root.join("src/routes/health.rs"),
        "pub async fn health() -> &'static str {\n    \"ok\"\n}\n",
    )?;
    write_file(
        &root.join("src/routes/ws.rs"),
        "pub async fn ws_upgrade_placeholder() -> &'static str {\n    \"websocket endpoint placeholder\"\n}\n",
    )?;
    write_file(
        &root.join("src/realtime/event_bus.rs"),
        "pub fn publish_event_placeholder(topic: &str, payload: &str) {\n    println!(\"publish to {topic}: {payload}\");\n}\n",
    )?;
    write_config_files(root, "dev")?;
    patch_docker_app_name(root, name)?;
    Ok(())
}

fn write_main(root: &Path) -> Result<()> {
    write_file(
        &root.join("src/main.rs"),
        "mod app;\n\nuse hwhkit::{config_v2::BootstrapConfig, run_v2};\n\n#[tokio::main]\nasync fn main() {\n    let bootstrap = BootstrapConfig::default();\n\n    match run_v2(app::App, bootstrap).await {\n        Ok(built) => {\n            println!(\"bootstrap completed\");\n            println!(\"applied sources: {:?}\", built.applied_sources);\n            println!(\"initialized integrations: {:?}\", built.initialized_integrations);\n            println!(\"degraded integrations: {:?}\", built.degraded_integrations);\n            println!(\"next: wire router/server runtime in app-specific entrypoint\");\n        }\n        Err(err) => {\n            eprintln!(\"bootstrap failed: {err}\");\n            std::process::exit(1);\n        }\n    }\n}\n",
    )
}

fn write_standard_app(root: &Path) -> Result<()> {
    write_file(
        &root.join("src/app.rs"),
        "use async_trait::async_trait;\nuse hwhkit::{\n    config_v2::AppConfig,\n    core_v2::{AppContext, Application, Result},\n    get, Router,\n};\n\npub struct App;\n\n#[async_trait]\nimpl Application for App {\n    async fn build_router(&self, _ctx: AppContext, _cfg: &AppConfig) -> Result<Router> {\n        Ok(Router::new().route(\"/healthz\", get(health)))\n    }\n}\n\nasync fn health() -> &'static str {\n    \"ok\"\n}\n",
    )
}

fn write_config_files(root: &Path, env_name: &str) -> Result<()> {
    write_file(
        &root.join("config/default.toml"),
        "[server]\nhost = \"0.0.0.0\"\nport = 3000\n\n[observability]\nservice_name = \"app\"\nenvironment = \"dev\"\n\n[observability.logging]\nlevel = \"info\"\nformat = \"pretty\"\n",
    )?;
    write_file(&root.join(format!("config/{env_name}.toml")), "")?;
    write_file(&root.join("config/prod.toml"), "")?;
    Ok(())
}

fn cargo_toml(name: &str, features: &[&str]) -> String {
    let features = features
        .iter()
        .map(|f| format!("\"{f}\""))
        .collect::<Vec<_>>()
        .join(", ");

    format!(
        "[package]\nname = \"{name}\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[dependencies]\nasync-trait = \"0.1\"\nhwhkit = {{ version = \"0.2\", features = [{features}] }}\ntokio = {{ version = \"1\", features = [\"full\"] }}\n"
    )
}

fn patch_docker_app_name(root: &Path, name: &str) -> Result<()> {
    let dockerfile_path = root.join("Dockerfile");
    let current = fs::read_to_string(&dockerfile_path)
        .with_context(|| format!("failed to read {}", dockerfile_path.display()))?;
    let patched = current.replace("APP_NAME", name);
    write_file(&dockerfile_path, &patched)
}

fn package_name_from_root(root: &Path) -> Result<String> {
    let Some(file_name) = root.file_name().and_then(|v| v.to_str()) else {
        anyhow::bail!("invalid project path: {}", root.display());
    };

    let normalized = file_name.replace('_', "-");
    if normalized.trim().is_empty() {
        anyhow::bail!("project name cannot be empty");
    }

    Ok(normalized)
}

fn write_file(path: &Path, content: &str) -> Result<()> {
    fs::write(path, content).with_context(|| format!("failed to write {}", path.display()))
}

fn template_name(template: TemplateKind) -> &'static str {
    match template {
        TemplateKind::MinimalApi => "minimal-api",
        TemplateKind::ApiGrpc => "api-grpc",
        TemplateKind::RealtimeEvent => "realtime-event",
    }
}
